[2021-06-08 19:40:16,106] cloud69/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2021-06-08 19:40:16,108] cloud69/INFO/locust.main: Starting Locust 1.5.3
[2021-06-08 19:40:16,735] cloud69/INFO/locust.runners: Spawning 12 users at the rate 0.25 users/s (0 users already running)...
[2021-06-08 19:40:57,729] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:41:00,752] cloud69/INFO/locust.runners: All users spawned: SimulateUserBenchmark: 12 (12 total running)
[2021-06-08 19:41:24,348] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:41:32,749] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:41:52,761] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:41:52,762] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:41:52,770] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:41:52,809] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:42:07,683] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:42:07,685] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:42:21,319] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:42:59,119] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:43:16,513] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:43:23,356] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:43:37,652] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:44:11,744] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:45:46,040] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:46:47,645] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:47:19,952] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:48:05,648] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:48:07,021] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:48:54,153] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:49:04,781] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:49:16,464] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:49:26,930] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:49:36,810] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:49:47,068] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:50:05,943] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:50:13,925] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:50:29,315] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:50:58,316] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:50:59,646] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:52:25,707] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:52:43,112] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:53:48,594] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:54:46,601] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 19:55:16,735] cloud69/INFO/locust.runners: Stopping 12 users
[2021-06-08 19:55:16,738] cloud69/INFO/locust.runners: 12 Users have been stopped, 0 still running
[2021-06-08 19:55:16,739] cloud69/INFO/locust.runners: Got quit message from master, shutting down...
[2021-06-08 19:55:16,739] cloud69/INFO/locust.main: Running teardowns...
[2021-06-08 19:55:16,739] cloud69/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-06-08 19:55:16,739] cloud69/INFO/locust.main: Cleaning up runner...
