Count,Message,Traceback,Nodes
18,Cannot choose from an empty sequence,"  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/simulateUser.py"", line 37, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 5, 0, _, 6, a, 3, 0, 2, e, c, 3, e, 1, 6, a, 4, e, 9, 6, 9, 9, a, e, 7, c, 8, 8, 0, 3, 3, b, 2, 3, b, d, ,,  , c, l, o, u, d, 5, 0, _, 0, c, f, 1, 2, 8, 2, b, 2, c, a, 9, 4, 6, d, 9, b, a, 7, c, f, 7, e, 4, 6, 4, e, 7, f, 0, c, 8"
8,Cannot choose from an empty sequence,"  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/simulateUser.py"", line 37, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 6, 9, _, 3, 2, 4, 1, 6, e, c, c, 4, 2, 8, 0, 4, 6, c, a, b, 9, c, 6, 4, e, e, 3, c, 3, 5, 5, 1, b, 6, c, ,,  , c, l, o, u, d, 6, 9, _, 3, f, d, a, 3, 4, 3, a, 7, 9, 9, 1, 4, 1, b, b, 8, 6, 1, c, b, f, 3, 7, 2, a, 6, 9, d, a, a, e"
