[2021-05-27 16:11:10,415] cloud69/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2021-05-27 16:11:10,416] cloud69/INFO/locust.main: Starting Locust 1.5.3
[2021-05-27 16:11:11,375] cloud69/INFO/locust.runners: Spawning 25 users at the rate 0.5 users/s (0 users already running)...
[2021-05-27 16:11:59,400] cloud69/INFO/locust.runners: All users spawned: StaticBenchmarkRead: 25 (25 total running)
[2021-05-27 16:17:51,875] cloud69/ERROR/locust.user.task: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/staticRead.py", line 14, in readPage
    page = actions.getSinglePage(self)
  File "/home/gsd/benchmark/wiki/locustfiles/actions/content.py", line 110, in getSinglePage
    page_tree = list(filter(lambda x: GENERATED_FOLDER_PREFIX in x["title"], graphqlQueries.pageTreeInParent(httpUser, 0)))
  File "/home/gsd/benchmark/wiki/locustfiles/actions/graphqlQueries.py", line 9, in pageTreeInParent
    return graphqlQuery(httpUser, "Query Page Tree", readFile("queries/pageTreeInParent.graphql"), {"parent": parent})["data"]["pages"]["tree"]
  File "/home/gsd/benchmark/wiki/locustfiles/actions/graphqlQueries.py", line 6, in graphqlQuery
    return httpUser.client.post(url="/graphql", name=name, json={"query": query, "variables": variables}, headers={"Connection": "keep-alive", "Authorization": "Bearer {}".format(httpUser.token if hasattr(httpUser, "token") and auth else "")}).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2021-05-27 16:21:14,380] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/staticRead.py", line 20, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-05-27 16:21:14,503] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/staticRead.py", line 20, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-05-27 16:22:45,297] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/staticRead.py", line 20, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-05-27 16:24:03,721] cloud69/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/staticRead.py", line 20, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-05-27 16:26:11,378] cloud69/INFO/locust.runners: Stopping 25 users
[2021-05-27 16:26:11,383] cloud69/INFO/locust.runners: 25 Users have been stopped, 0 still running
[2021-05-27 16:26:11,383] cloud69/INFO/locust.runners: Got quit message from master, shutting down...
[2021-05-27 16:26:11,384] cloud69/INFO/locust.main: Running teardowns...
[2021-05-27 16:26:11,384] cloud69/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-05-27 16:26:11,384] cloud69/INFO/locust.main: Cleaning up runner...
